export const servicesMockData = [
  {
    serviceId: 1,
    serviceName: "Span",
    disabled: false,
    createdBy: "Amitie Donan",
    createdAt: "2023-12-11",
    modifiedBy: "志宸",
    modifiedAt: "2023-09-21",
  },
  {
    serviceId: 2,
    serviceName: "Fix San",
    disabled: false,
    createdBy: "Shandy Fowles",
    createdAt: "2023-03-06",
    modifiedBy: "羽彤",
    modifiedAt: "2023-09-17",
  },
  {
    serviceId: 3,
    serviceName: "Voltsillam",
    disabled: true,
    createdBy: "Ivan Fullilove",
    createdAt: "2023-11-29",
    modifiedBy: "皓睿",
    modifiedAt: "2023-03-31",
  },
  {
    serviceId: 4,
    serviceName: "Job",
    disabled: true,
    createdBy: "Edith Hardstaff",
    createdAt: "2023-08-20",
    modifiedBy: "佐仪",
    modifiedAt: "2024-01-07",
  },
  {
    serviceId: 5,
    serviceName: "Regrant",
    disabled: false,
    createdBy: "Kelsi Hawtin",
    createdAt: "2023-06-28",
    modifiedBy: "品逸",
    modifiedAt: "2023-02-27",
  },
  {
    serviceId: 6,
    serviceName: "Tempsoft",
    disabled: false,
    createdBy: "Eduard Jamison",
    createdAt: "2023-05-06",
    modifiedBy: "羽彤",
    modifiedAt: "2023-06-22",
  },
  {
    serviceId: 7,
    serviceName: "Matsoft",
    disabled: false,
    createdBy: "Yance Mcimmie",
    createdAt: "2023-05-22",
    modifiedBy: "泰霖",
    modifiedAt: "2023-06-01",
  },
  {
    serviceId: 8,
    serviceName: "Aerified",
    disabled: false,
    createdBy: "Sheff Killik",
    createdAt: "2023-02-26",
    modifiedBy: "睿杰",
    modifiedAt: "2023-07-10",
  },
  {
    serviceId: 9,
    serviceName: "Home Ing",
    disabled: false,
    createdBy: "Seward Nutley",
    createdAt: "2024-02-16",
    modifiedBy: "雨萌",
    modifiedAt: "2023-11-26",
  },
  {
    serviceId: 10,
    serviceName: "Stim",
    disabled: false,
    createdBy: "Vicky Ramel",
    createdAt: "2023-12-15",
    modifiedBy: "香茹",
    modifiedAt: "2023-10-30",
  },
];
