export const storesMockData = [
  {
    hqCd: 6,
    hqName: "Rebel Distributors Corp",
    storeCd: 54,
    storeName: "Birchwood",
    email: "amaytom0@issuu.com",
    ftpUser: "amaytom0",
    ftpPass: "aA6'.45cWRUEf!.X",
    disabled: false,
    createdBy: "Gennie Heasman",
    createdAt: "2023-09-05T05:26:10Z",
    modifiedBy: "Alfie Maytom",
    modifiedAt: "2023-12-11T09:03:57Z",
  },
  {
    hqCd: 22,
    hqName: "Project, Inc.",
    storeCd: 68,
    storeName: "Holmberg",
    email: "adomenc1@intel.com",
    ftpUser: "adomenc1",
    ftpPass: "rX9},6P%sZhL08",
    disabled: false,
    createdBy: "Agathe Breinl",
    createdAt: "2023-05-11T14:44:55Z",
    modifiedBy: "Avis Domenc",
    modifiedAt: "2023-07-04T04:31:59Z",
  },
  {
    hqCd: 82,
    hqName: "Coty US LLC",
    storeCd: 53,
    storeName: "Hintze",
    email: "mrowaszkiewicz2@ifeng.com",
    ftpUser: "mrowaszkiewicz2",
    ftpPass: "bQ2,}!<fpUH",
    disabled: false,
    createdBy: "Dewitt Wilkins",
    createdAt: "2023-08-05T06:30:22Z",
    modifiedBy: "Marlo Rowaszkiewicz",
    modifiedAt: "2023-07-24T16:30:35Z",
  },
  {
    hqCd: 13,
    hqName: "Western Family Foods, Inc",
    storeCd: 14,
    storeName: "Butterfield",
    email: "ibranney3@wikimedia.org",
    ftpUser: "ibranney3",
    ftpPass: 'yB3."XGRfkm,y',
    disabled: true,
    createdBy: "Deni Bakhrushkin",
    createdAt: "2023-12-21T07:10:32Z",
    modifiedBy: "Ilene Branney",
    modifiedAt: "2023-06-02T19:47:12Z",
  },
  {
    hqCd: 11,
    hqName: "Rebel Distributors Corp",
    storeCd: 7,
    storeName: "Merchant",
    email: "bmillin4@lycos.com",
    ftpUser: "bmillin4",
    ftpPass: "vO0#_i#+'",
    disabled: false,
    createdBy: "Galvan Alford",
    createdAt: "2023-03-17T07:50:16Z",
    modifiedBy: "Benito Millin",
    modifiedAt: "2023-11-19T22:00:03Z",
  },
  {
    hqCd: 27,
    hqName: "King Bio Inc.",
    storeCd: 85,
    storeName: "Westridge",
    email: "jkyston5@smh.com.au",
    ftpUser: "jkyston5",
    ftpPass: "hY7(PGaX@}_AT{%",
    disabled: true,
    createdBy: "Morissa Rooksby",
    createdAt: "2023-11-21T07:55:14Z",
    modifiedBy: "Jone Kyston",
    modifiedAt: "2023-05-27T18:07:29Z",
  },
  {
    hqCd: 73,
    hqName: "Ventura Corporation LTD.",
    storeCd: 100,
    storeName: "Everett",
    email: "hmckeever6@blogspot.com",
    ftpUser: "hmckeever6",
    ftpPass: "kV0&<#$x#8CV!",
    disabled: false,
    createdBy: "Julietta Duddridge",
    createdAt: "2023-09-30T06:23:07Z",
    modifiedBy: "Hermy McKeever",
    modifiedAt: "2023-06-02T19:25:32Z",
  },
  {
    hqCd: 83,
    hqName: "Ventura Corporation LTD",
    storeCd: 16,
    storeName: "Montana",
    email: "kserjeant7@ucoz.ru",
    ftpUser: "kserjeant7",
    ftpPass: "gG3/5w@/D4&xf",
    disabled: true,
    createdBy: "Maximo Robertot",
    createdAt: "2023-11-14T06:01:37Z",
    modifiedBy: "Koren Serjeant",
    modifiedAt: "2023-04-19T19:34:13Z",
  },
  {
    hqCd: 83,
    hqName: "PD-Rx Pharmaceuticals, Inc.",
    storeCd: 25,
    storeName: "Autumn Leaf",
    email: "cleadstone8@bravesites.com",
    ftpUser: "cleadstone8",
    ftpPass: "jD1+%d&X|8i|>Y",
    disabled: true,
    createdBy: "Angil Hannis",
    createdAt: "2023-11-22T22:24:12Z",
    modifiedBy: "Chloette Leadstone",
    modifiedAt: "2023-08-10T19:56:44Z",
  },
  {
    hqCd: 2,
    hqName: "L. Perrigo Company",
    storeCd: 51,
    storeName: "Fuller",
    email: "jann9@latimes.com",
    ftpUser: "jann9",
    ftpPass: "gK4>6gBk5lj",
    disabled: true,
    createdBy: "Bette Hazeup",
    createdAt: "2023-05-22T20:52:02Z",
    modifiedBy: "Jo ann Sare",
    modifiedAt: "2023-12-19T08:17:32Z",
  },
  {
    hqCd: 71,
    hqName: "Pfizer Laboratories Div Pfizer Inc.",
    storeCd: 24,
    storeName: "Morningstar",
    email: "rgratrexa@bluehost.com",
    ftpUser: "rgratrexa",
    ftpPass: "aJ1+iiQ+Z",
    disabled: true,
    createdBy: "Elias Jonk",
    createdAt: "2023-11-24T11:02:27Z",
    modifiedBy: "Rayna Gratrex",
    modifiedAt: "2023-03-14T21:49:07Z",
  },
  {
    hqCd: 55,
    hqName: "AstraZeneca Pharmaceuticals LP",
    storeCd: 4,
    storeName: "Donald",
    email: "pfitzhenryb@digg.com",
    ftpUser: "pfitzhenryb",
    ftpPass: "qY4*9#=#<z2",
    disabled: false,
    createdBy: "Flem Hilldrup",
    createdAt: "2023-03-19T19:59:59Z",
    modifiedBy: "Pegeen Fitzhenry",
    modifiedAt: "2024-01-22T23:25:41Z",
  },
  {
    hqCd: 31,
    hqName: "Dynarex Corporation",
    storeCd: 68,
    storeName: "Pennsylvania",
    email: "kprophetc@moonfruit.com",
    ftpUser: "kprophetc",
    ftpPass: "iU8(>4NkPj%n,+xg",
    disabled: false,
    createdBy: "Fernando Capelle",
    createdAt: "2023-05-16T12:08:55Z",
    modifiedBy: "Kleon Prophet",
    modifiedAt: "2023-07-18T11:06:27Z",
  },
  {
    hqCd: 50,
    hqName: "St Marys Medical Park Pharmacy",
    storeCd: 29,
    storeName: "Meadow Vale",
    email: "jeffnertd@technorati.com",
    ftpUser: "jeffnertd",
    ftpPass: "fS9>MJe)/fX!4tu~",
    disabled: false,
    createdBy: "Sephira Thurbon",
    createdAt: "2023-04-11T10:21:38Z",
    modifiedBy: "Juanita Effnert",
    modifiedAt: "2023-11-14T04:59:43Z",
  },
  {
    hqCd: 75,
    hqName: "Lake Erie Medical & Surgical Supply DBA Quality Care Products LLC",
    storeCd: 52,
    storeName: "Donald",
    email: "ntonkinsone@purevolume.com",
    ftpUser: "ntonkinsone",
    ftpPass: "kV3!p0E~W",
    disabled: false,
    createdBy: "Craggy Clowes",
    createdAt: "2024-02-02T00:38:38Z",
    modifiedBy: "Nanette Tonkinson",
    modifiedAt: "2024-01-08T20:40:33Z",
  },
  {
    hqCd: 4,
    hqName: "American Health Packaging",
    storeCd: 21,
    storeName: "Parkside",
    email: "lyaninf@bing.com",
    ftpUser: "lyaninf",
    ftpPass: "gJ1'W=vLXh=b'",
    disabled: true,
    createdBy: "Judie Burberry",
    createdAt: "2023-07-03T06:03:43Z",
    modifiedBy: "Lombard Yanin",
    modifiedAt: "2024-01-30T08:19:27Z",
  },
  {
    hqCd: 98,
    hqName: "Bryant Ranch Prepack",
    storeCd: 15,
    storeName: "Orin",
    email: "fnowakowskig@huffingtonpost.com",
    ftpUser: "fnowakowskig",
    ftpPass: "jL6`G|{`",
    disabled: false,
    createdBy: "Tamarra Jordan",
    createdAt: "2023-08-06T16:12:06Z",
    modifiedBy: "Filberte Nowakowski",
    modifiedAt: "2023-02-28T23:46:40Z",
  },
  {
    hqCd: 73,
    hqName: "Lake Erie Medical DBA Quality Care Products LLC",
    storeCd: 1,
    storeName: "Sutteridge",
    email: "gacklandh@delicious.com",
    ftpUser: "gacklandh",
    ftpPass: "vG4@*iwaf+@y%n@!",
    disabled: false,
    createdBy: "Lancelot Doust",
    createdAt: "2023-06-02T18:38:01Z",
    modifiedBy: "Gracia Ackland",
    modifiedAt: "2023-08-10T12:56:23Z",
  },
  {
    hqCd: 62,
    hqName: "AMI Cosmetic Co.,Ltd.",
    storeCd: 37,
    storeName: "Meadow Ridge",
    email: "wbarmei@slashdot.org",
    ftpUser: "wbarmei",
    ftpPass: "fJ2'7y18G6r",
    disabled: true,
    createdBy: "Roderic Cogan",
    createdAt: "2023-07-20T09:38:49Z",
    modifiedBy: "Winny Barme",
    modifiedAt: "2023-12-28T18:55:53Z",
  },
  {
    hqCd: 4,
    hqName: "Cardinal Health",
    storeCd: 68,
    storeName: "Northwestern",
    email: "jwiffenj@merriam-webster.com",
    ftpUser: "jwiffenj",
    ftpPass: "vL7}ERRa~",
    disabled: true,
    createdBy: "Nertie Lody",
    createdAt: "2023-06-26T00:55:31Z",
    modifiedBy: "Jon Wiffen",
    modifiedAt: "2023-03-06T15:27:41Z",
  },
  {
    hqCd: 65,
    hqName: "Natural Health Supply",
    storeCd: 13,
    storeName: "Melrose",
    email: "rboughtflowerk@bizjournals.com",
    ftpUser: "rboughtflowerk",
    ftpPass: "iH9=nH_T~s",
    disabled: false,
    createdBy: "Katrina Cuskery",
    createdAt: "2023-05-02T17:45:09Z",
    modifiedBy: "Rhonda Boughtflower",
    modifiedAt: "2023-04-14T15:18:03Z",
  },
  {
    hqCd: 40,
    hqName: "Allergy Laboratories, Inc.",
    storeCd: 32,
    storeName: "Sunbrook",
    email: "rstuehmeyerl@unicef.org",
    ftpUser: "rstuehmeyerl",
    ftpPass: "jO2=Ctc>{BNRlO",
    disabled: false,
    createdBy: "Corey Rizzolo",
    createdAt: "2023-03-19T04:00:36Z",
    modifiedBy: "Rasla Stuehmeyer",
    modifiedAt: "2023-04-14T04:19:35Z",
  },
  {
    hqCd: 92,
    hqName: "Washington Homeopathic Products",
    storeCd: 51,
    storeName: "Vera",
    email: "glicasm@adobe.com",
    ftpUser: "glicasm",
    ftpPass: "wL3)+@7DxOg*",
    disabled: false,
    createdBy: "Gay Cureton",
    createdAt: "2023-08-05T11:21:53Z",
    modifiedBy: "Guillermo Licas",
    modifiedAt: "2023-02-27T13:30:02Z",
  },
  {
    hqCd: 25,
    hqName: "HOMEOLAB USA INC",
    storeCd: 12,
    storeName: "Eastwood",
    email: "vmcbradyn@google.ca",
    ftpUser: "vmcbradyn",
    ftpPass: "wW8!1`Q{Ug(Wz",
    disabled: false,
    createdBy: "Taylor Aykroyd",
    createdAt: "2023-04-05T03:58:38Z",
    modifiedBy: "Venita McBrady",
    modifiedAt: "2023-09-26T01:11:35Z",
  },
  {
    hqCd: 8,
    hqName: "Mylan Pharmaceuticals Inc.",
    storeCd: 37,
    storeName: "Artisan",
    email: "ryendallo@squarespace.com",
    ftpUser: "ryendallo",
    ftpPass: "rF9\\lTWkHu73V",
    disabled: false,
    createdBy: "Frederich Heiden",
    createdAt: "2024-02-18T20:42:30Z",
    modifiedBy: "Randolph Yendall",
    modifiedAt: "2024-01-01T08:22:01Z",
  },
  {
    hqCd: 33,
    hqName: "American Sales Company",
    storeCd: 82,
    storeName: "Superior",
    email: "jstorerp@mayoclinic.com",
    ftpUser: "jstorerp",
    ftpPass: "yB7~L~&t",
    disabled: true,
    createdBy: "Reg Halbeard",
    createdAt: "2023-02-25T09:29:50Z",
    modifiedBy: "Jewel Storer",
    modifiedAt: "2023-02-23T18:47:27Z",
  },
  {
    hqCd: 60,
    hqName: "Personal Care Products",
    storeCd: 18,
    storeName: "Golf Course",
    email: "kgolleyq@reddit.com",
    ftpUser: "kgolleyq",
    ftpPass: "cX7{V#_W<V",
    disabled: true,
    createdBy: "Harrie Bingall",
    createdAt: "2023-08-03T16:07:14Z",
    modifiedBy: "Kimmie Golley",
    modifiedAt: "2023-06-08T09:37:46Z",
  },
  {
    hqCd: 63,
    hqName: "Physicians Total Care, inc.",
    storeCd: 7,
    storeName: "Carpenter",
    email: "acawthorner@upenn.edu",
    ftpUser: "acawthorner",
    ftpPass: "gI6<v~w_Vv}\\8",
    disabled: true,
    createdBy: "Sidonnie Quincey",
    createdAt: "2024-01-01T22:49:41Z",
    modifiedBy: "Audi Cawthorne",
    modifiedAt: "2024-02-02T21:55:59Z",
  },
  {
    hqCd: 65,
    hqName: "King Bio Inc.",
    storeCd: 45,
    storeName: "Upham",
    email: "pbarrats@pagesperso-orange.fr",
    ftpUser: "pbarrats",
    ftpPass: 'mC9!T=k5"&',
    disabled: false,
    createdBy: "Daria Ponton",
    createdAt: "2023-06-02T19:10:21Z",
    modifiedBy: "Phedra Barrat",
    modifiedAt: "2023-10-25T08:05:39Z",
  },
  {
    hqCd: 67,
    hqName: "DHC USA Incorporated",
    storeCd: 17,
    storeName: "International",
    email: "nbakeyt@answers.com",
    ftpUser: "nbakeyt",
    ftpPass: "kI8=c\\1}i(",
    disabled: true,
    createdBy: "Raven Arney",
    createdAt: "2023-12-20T20:25:43Z",
    modifiedBy: "Nicolis Bakey",
    modifiedAt: "2023-11-21T10:14:07Z",
  },
  {
    hqCd: 85,
    hqName: "Conopco Inc. d/b/a Unilever",
    storeCd: 43,
    storeName: "Ruskin",
    email: "mlattimoreu@pbs.org",
    ftpUser: "mlattimoreu",
    ftpPass: "sA6&x9?Y$JPj$",
    disabled: false,
    createdBy: "Kacie Justham",
    createdAt: "2023-06-10T11:20:40Z",
    modifiedBy: "Maryjane Lattimore",
    modifiedAt: "2023-09-22T22:17:40Z",
  },
  {
    hqCd: 16,
    hqName: "ALK-Abello, Inc.",
    storeCd: 34,
    storeName: "Susan",
    email: "brixv@nasa.gov",
    ftpUser: "brixv",
    ftpPass: "gR1+=UgLn<!}!w",
    disabled: false,
    createdBy: "Olympe Tatlowe",
    createdAt: "2024-02-16T11:04:14Z",
    modifiedBy: "Brocky Rix",
    modifiedAt: "2023-07-26T17:32:27Z",
  },
  {
    hqCd: 64,
    hqName: "NARS Cosmetics",
    storeCd: 80,
    storeName: "Straubel",
    email: "eebbersw@quantcast.com",
    ftpUser: "eebbersw",
    ftpPass: "lI8<_SGSLE",
    disabled: false,
    createdBy: "Anne-marie Dhennin",
    createdAt: "2023-11-11T12:46:27Z",
    modifiedBy: "Elihu Ebbers",
    modifiedAt: "2023-07-02T10:24:13Z",
  },
  {
    hqCd: 89,
    hqName: "REMEDYREPACK INC.",
    storeCd: 9,
    storeName: "Birchwood",
    email: "jhadekex@people.com.cn",
    ftpUser: "jhadekex",
    ftpPass: "jF9#_dI>`/'gu",
    disabled: true,
    createdBy: "Gregory Blenkinship",
    createdAt: "2024-01-10T04:31:11Z",
    modifiedBy: "Jarib Hadeke",
    modifiedAt: "2023-05-11T09:35:06Z",
  },
  {
    hqCd: 57,
    hqName: "Paddock Laboratories, LLC",
    storeCd: 40,
    storeName: "Briar Crest",
    email: "pchassony@cisco.com",
    ftpUser: "pchassony",
    ftpPass: "gW7,SB\\?@tj",
    disabled: false,
    createdBy: "Moll Kanter",
    createdAt: "2023-06-07T08:39:05Z",
    modifiedBy: "Pieter Chasson",
    modifiedAt: "2024-01-05T16:31:17Z",
  },
  {
    hqCd: 19,
    hqName: "SHISEIDO AMERICAS CORPORATION",
    storeCd: 96,
    storeName: "Oxford",
    email: "mtourniez@toplist.cz",
    ftpUser: "mtourniez",
    ftpPass: "oG1!$$K+",
    disabled: true,
    createdBy: "Irena Lamey",
    createdAt: "2023-10-23T11:15:58Z",
    modifiedBy: "Merlina Tournie",
    modifiedAt: "2023-05-07T03:24:20Z",
  },
  {
    hqCd: 68,
    hqName: "Mylan Pharmaceuticals Inc.",
    storeCd: 53,
    storeName: "Roxbury",
    email: "edawnay10@mail.ru",
    ftpUser: "edawnay10",
    ftpPass: "kO4%x0O`nwO`j",
    disabled: true,
    createdBy: "Ned Benbrick",
    createdAt: "2023-09-13T23:06:46Z",
    modifiedBy: "Eadie Dawnay",
    modifiedAt: "2023-08-05T02:07:41Z",
  },
  {
    hqCd: 15,
    hqName: "Proficient Rx LP",
    storeCd: 86,
    storeName: "Wayridge",
    email: "whollyar11@opensource.org",
    ftpUser: "whollyar11",
    ftpPass: "vT1\\wstniem=*DK",
    disabled: false,
    createdBy: "Gus Semaine",
    createdAt: "2023-07-12T22:41:03Z",
    modifiedBy: "Worth Hollyar",
    modifiedAt: "2023-08-02T18:01:22Z",
  },
  {
    hqCd: 10,
    hqName: "American Sales Company",
    storeCd: 76,
    storeName: "Thompson",
    email: "gpauleau12@sogou.com",
    ftpUser: "gpauleau12",
    ftpPass: "qJ3>uSKQ",
    disabled: false,
    createdBy: "Evelyn Dowson",
    createdAt: "2024-02-02T03:00:41Z",
    modifiedBy: "Gerrie Pauleau",
    modifiedAt: "2023-08-03T23:41:01Z",
  },
  {
    hqCd: 16,
    hqName: "Preferred Pharmaceuticals, Inc",
    storeCd: 98,
    storeName: "Randy",
    email: "jpemberton13@prnewswire.com",
    ftpUser: "jpemberton13",
    ftpPass: "wE3~UzZHu}jn",
    disabled: false,
    createdBy: "Bengt Nind",
    createdAt: "2023-08-05T07:39:01Z",
    modifiedBy: "Jone Pemberton",
    modifiedAt: "2023-03-31T23:50:40Z",
  },
  {
    hqCd: 7,
    hqName: "La Prairie, Inc.",
    storeCd: 46,
    storeName: "Oneill",
    email: "ipopley14@simplemachines.org",
    ftpUser: "ipopley14",
    ftpPass: "hM5(uA%YXKb",
    disabled: false,
    createdBy: "Olivie Nyssen",
    createdAt: "2024-01-07T05:42:53Z",
    modifiedBy: "Ignace Popley",
    modifiedAt: "2024-01-19T17:39:17Z",
  },
  {
    hqCd: 78,
    hqName: "Cardinal Health",
    storeCd: 81,
    storeName: "Heath",
    email: "cduckering15@qq.com",
    ftpUser: "cduckering15",
    ftpPass: "eP1&QyLq4l&L{v",
    disabled: false,
    createdBy: "Staford Hardacre",
    createdAt: "2023-09-15T12:33:28Z",
    modifiedBy: "Cosmo Duckering",
    modifiedAt: "2023-06-07T18:28:16Z",
  },
  {
    hqCd: 97,
    hqName: "BNP Industries Inc.",
    storeCd: 41,
    storeName: "Westridge",
    email: "pbettley16@amazon.com",
    ftpUser: "pbettley16",
    ftpPass: "gC4{Qd}G+U",
    disabled: false,
    createdBy: "Cassandry Adelsberg",
    createdAt: "2023-08-30T21:42:59Z",
    modifiedBy: "Putnem Bettley",
    modifiedAt: "2023-10-05T03:51:55Z",
  },
  {
    hqCd: 45,
    hqName: "AMERICAN SALES COMPANY",
    storeCd: 49,
    storeName: "Nova",
    email: "lgyrgorwicx17@house.gov",
    ftpUser: "lgyrgorwicx17",
    ftpPass: "vU7`?yzMG{c=QXd",
    disabled: true,
    createdBy: "Kerr Briskey",
    createdAt: "2023-09-05T10:30:45Z",
    modifiedBy: "Lorie Gyrgorwicx",
    modifiedAt: "2023-11-13T23:51:49Z",
  },
  {
    hqCd: 65,
    hqName: "Bioelements, Inc.",
    storeCd: 99,
    storeName: "Linden",
    email: "bosmond18@springer.com",
    ftpUser: "bosmond18",
    ftpPass: "fX1+nYO(8u#}.}",
    disabled: false,
    createdBy: "Fanya Matheson",
    createdAt: "2023-03-02T14:15:39Z",
    modifiedBy: "Berenice Osmond",
    modifiedAt: "2023-09-20T13:40:17Z",
  },
  {
    hqCd: 80,
    hqName: "Mylan Pharmaceuticals Inc.",
    storeCd: 8,
    storeName: "Gina",
    email: "gmimmack19@naver.com",
    ftpUser: "gmimmack19",
    ftpPass: "dC6?sKbAuojM/6m",
    disabled: true,
    createdBy: "Anthony Annell",
    createdAt: "2023-04-01T00:31:14Z",
    modifiedBy: "Gwennie Mimmack",
    modifiedAt: "2023-07-23T20:33:09Z",
  },
  {
    hqCd: 85,
    hqName: "Purdue Pharma LP",
    storeCd: 25,
    storeName: "Hauk",
    email: "rmoreby1a@toplist.cz",
    ftpUser: "rmoreby1a",
    ftpPass: "cZ6{)#|8sJB",
    disabled: false,
    createdBy: "Bald Pfeffel",
    createdAt: "2024-02-17T04:57:16Z",
    modifiedBy: "Reinwald Moreby",
    modifiedAt: "2023-04-18T09:11:43Z",
  },
  {
    hqCd: 21,
    hqName: "TOP CARE (Topco Associates LLC)",
    storeCd: 9,
    storeName: "Pine View",
    email: "wclemmow1b@shutterfly.com",
    ftpUser: "wclemmow1b",
    ftpPass: "uS9}0HRH!*Z0f$",
    disabled: true,
    createdBy: "Philip Culp",
    createdAt: "2024-02-02T19:10:42Z",
    modifiedBy: "Wally Clemmow",
    modifiedAt: "2024-01-26T14:32:47Z",
  },
  {
    hqCd: 25,
    hqName: "Ventura Corporation LTD",
    storeCd: 98,
    storeName: "Gina",
    email: "tallflatt1c@youku.com",
    ftpUser: "tallflatt1c",
    ftpPass: "jA0@~|U@",
    disabled: false,
    createdBy: "Russ Cowgill",
    createdAt: "2023-11-18T22:31:28Z",
    modifiedBy: "Thaddus Allflatt",
    modifiedAt: "2023-03-02T15:38:18Z",
  },
  {
    hqCd: 29,
    hqName: "Procter & Gamble Manufacturing Company",
    storeCd: 33,
    storeName: "Spohn",
    email: "ffarmery1d@barnesandnoble.com",
    ftpUser: "ffarmery1d",
    ftpPass: "oR2*mlH$uZ\\j\\{.W",
    disabled: false,
    createdBy: "Clarette Southworth",
    createdAt: "2023-10-05T19:00:47Z",
    modifiedBy: "Francisca Farmery",
    modifiedAt: "2023-03-03T11:33:31Z",
  },
  {
    hqCd: 90,
    hqName: "Physicians Total Care, Inc.",
    storeCd: 93,
    storeName: "Welch",
    email: "vhurry1e@hhs.gov",
    ftpUser: "vhurry1e",
    ftpPass: "fW9/SDAo7gs_D~,C",
    disabled: true,
    createdBy: "Kaye Jackman",
    createdAt: "2023-03-23T02:20:19Z",
    modifiedBy: "Violet Hurry",
    modifiedAt: "2023-06-10T00:01:31Z",
  },
  {
    hqCd: 1,
    hqName: "Lake Erie Medical & Surgical Supply DBA Quality Care Produtcs LLC",
    storeCd: 57,
    storeName: "Armistice",
    email: "aivashev1f@example.com",
    ftpUser: "aivashev1f",
    ftpPass: 'rZ7`"L`tVzn7/',
    disabled: true,
    createdBy: "Dean Redpath",
    createdAt: "2023-03-12T04:29:19Z",
    modifiedBy: "Arabelle Ivashev",
    modifiedAt: "2024-02-04T22:14:29Z",
  },
  {
    hqCd: 10,
    hqName: "Genzyme Corporation",
    storeCd: 89,
    storeName: "Anniversary",
    email: "cvalencia1g@rediff.com",
    ftpUser: "cvalencia1g",
    ftpPass: "hM3\\rD/$",
    disabled: true,
    createdBy: "Price Bowne",
    createdAt: "2023-12-27T06:56:30Z",
    modifiedBy: "Chester Valencia",
    modifiedAt: "2023-07-31T04:09:16Z",
  },
  {
    hqCd: 79,
    hqName: "Ventura Corporation LTD.",
    storeCd: 4,
    storeName: "La Follette",
    email: "bbaumber1h@nature.com",
    ftpUser: "bbaumber1h",
    ftpPass: "vF0%\\Mxr",
    disabled: false,
    createdBy: "Erin Leavry",
    createdAt: "2023-02-20T04:59:19Z",
    modifiedBy: "Berton Baumber",
    modifiedAt: "2023-11-03T06:20:04Z",
  },
  {
    hqCd: 41,
    hqName: "Unit Dose Services",
    storeCd: 31,
    storeName: "Lighthouse Bay",
    email: "hmatschke1i@cloudflare.com",
    ftpUser: "hmatschke1i",
    ftpPass: "zQ3'w2rnl",
    disabled: true,
    createdBy: "Petr Gerrett",
    createdAt: "2023-06-20T02:33:51Z",
    modifiedBy: "Heinrik Matschke",
    modifiedAt: "2023-05-30T18:25:04Z",
  },
  {
    hqCd: 15,
    hqName: "Performance Health LLC",
    storeCd: 74,
    storeName: "Harbort",
    email: "adunford1j@businessinsider.com",
    ftpUser: "adunford1j",
    ftpPass: "fK9{U{(l",
    disabled: false,
    createdBy: "Laurel Tender",
    createdAt: "2023-12-02T14:39:28Z",
    modifiedBy: "Ally Dunford",
    modifiedAt: "2023-10-08T13:20:41Z",
  },
  {
    hqCd: 13,
    hqName: "Watson Laboratories, Inc.",
    storeCd: 54,
    storeName: "Bunker Hill",
    email: "kpesak1k@stanford.edu",
    ftpUser: "kpesak1k",
    ftpPass: "jF4&3/fqZ46_",
    disabled: false,
    createdBy: "Mordecai Walne",
    createdAt: "2023-05-05T22:04:49Z",
    modifiedBy: "Katha Pesak",
    modifiedAt: "2023-09-11T04:36:57Z",
  },
  {
    hqCd: 89,
    hqName: "AIRGAS-NORPAC INC.",
    storeCd: 62,
    storeName: "Ohio",
    email: "cchurchard1l@yellowbook.com",
    ftpUser: "cchurchard1l",
    ftpPass: "sR1?%_du6SCY3.QP",
    disabled: false,
    createdBy: "Fitz Gianulli",
    createdAt: "2024-01-22T08:46:23Z",
    modifiedBy: "Cissiee Churchard",
    modifiedAt: "2024-01-16T08:08:45Z",
  },
  {
    hqCd: 19,
    hqName: "Dental Technologies, Inc.",
    storeCd: 27,
    storeName: "Golf View",
    email: "gludye1m@facebook.com",
    ftpUser: "gludye1m",
    ftpPass: "eP8!/dfh~ad&1|@",
    disabled: true,
    createdBy: "Clemmie Scadden",
    createdAt: "2023-04-29T04:26:01Z",
    modifiedBy: "Granville Ludye",
    modifiedAt: "2024-01-02T16:27:43Z",
  },
  {
    hqCd: 52,
    hqName: "Wyeth Pharmaceuticals Company",
    storeCd: 67,
    storeName: "Pleasure",
    email: "sbates1n@surveymonkey.com",
    ftpUser: "sbates1n",
    ftpPass: "yL3{+Pjm,uX=V{k",
    disabled: false,
    createdBy: "Dotti Scrace",
    createdAt: "2024-02-04T22:19:52Z",
    modifiedBy: "Sampson Bates",
    modifiedAt: "2023-11-06T08:39:43Z",
  },
  {
    hqCd: 29,
    hqName: "Allergan, Inc.",
    storeCd: 43,
    storeName: "Grover",
    email: "lde1o@1688.com",
    ftpUser: "lde1o",
    ftpPass: 'wG1(.RT1"W',
    disabled: true,
    createdBy: "Pembroke Jewes",
    createdAt: "2023-08-22T05:18:18Z",
    modifiedBy: "Leigh De Laci",
    modifiedAt: "2023-11-22T16:05:10Z",
  },
  {
    hqCd: 8,
    hqName: "WALGREENS Co.",
    storeCd: 98,
    storeName: "Elmside",
    email: "clashmar1p@feedburner.com",
    ftpUser: "clashmar1p",
    ftpPass: "cN4+MJ>*J'",
    disabled: false,
    createdBy: "Marylinda Reye",
    createdAt: "2023-11-11T16:59:06Z",
    modifiedBy: "Cheston Lashmar",
    modifiedAt: "2023-11-02T09:59:26Z",
  },
  {
    hqCd: 41,
    hqName: "Newton Laboratories, Inc.",
    storeCd: 50,
    storeName: "Shasta",
    email: "tbucham1q@seesaa.net",
    ftpUser: "tbucham1q",
    ftpPass: 'oL4"l}cZ1',
    disabled: false,
    createdBy: "Pippo Erbain",
    createdAt: "2023-12-10T14:39:13Z",
    modifiedBy: "Tailor Bucham",
    modifiedAt: "2023-03-05T13:38:10Z",
  },
  {
    hqCd: 60,
    hqName: "STAT Rx USA LLC",
    storeCd: 16,
    storeName: "Fallview",
    email: "vmacailine1r@ebay.co.uk",
    ftpUser: "vmacailine1r",
    ftpPass: "hY7*_5EDHy'4",
    disabled: false,
    createdBy: "Sibley Fallowes",
    createdAt: "2023-09-26T10:06:18Z",
    modifiedBy: "Vannie MacAiline",
    modifiedAt: "2023-08-16T18:55:43Z",
  },
  {
    hqCd: 15,
    hqName: "Dolgencorp Inc",
    storeCd: 96,
    storeName: "Dovetail",
    email: "rtopper1s@independent.co.uk",
    ftpUser: "rtopper1s",
    ftpPass: "jV5$Q008roC'@",
    disabled: true,
    createdBy: "Noble Pescott",
    createdAt: "2024-01-17T12:57:55Z",
    modifiedBy: "Rachel Topper",
    modifiedAt: "2024-02-15T15:55:23Z",
  },
  {
    hqCd: 93,
    hqName: "Rij Pharmaceutical Corporation",
    storeCd: 7,
    storeName: "Hooker",
    email: "lhogsden1t@vkontakte.ru",
    ftpUser: "lhogsden1t",
    ftpPass: "yW9.%.(vxb*o",
    disabled: true,
    createdBy: "Maria Mathew",
    createdAt: "2023-08-19T10:38:13Z",
    modifiedBy: "Lesli Hogsden",
    modifiedAt: "2023-03-23T04:00:09Z",
  },
  {
    hqCd: 69,
    hqName: "Sandoz Inc",
    storeCd: 52,
    storeName: "Coolidge",
    email: "fcianni1u@vinaora.com",
    ftpUser: "fcianni1u",
    ftpPass: "hT6,hm7rfY#K}?Y",
    disabled: true,
    createdBy: "Cordey Sultana",
    createdAt: "2023-04-23T18:25:22Z",
    modifiedBy: "Fredrika Cianni",
    modifiedAt: "2023-03-27T22:30:43Z",
  },
  {
    hqCd: 57,
    hqName: "Deseret Biologicals, Inc.",
    storeCd: 5,
    storeName: "Summer Ridge",
    email: "cblanshard1v@psu.edu",
    ftpUser: "cblanshard1v",
    ftpPass: 'oO4=KZvQie"K%/Vt',
    disabled: false,
    createdBy: "Germayne Oppery",
    createdAt: "2024-01-01T03:50:02Z",
    modifiedBy: "Camila Blanshard",
    modifiedAt: "2023-11-26T11:08:50Z",
  },
  {
    hqCd: 91,
    hqName: "Health Mart",
    storeCd: 33,
    storeName: "Everett",
    email: "bheinig1w@liveinternet.ru",
    ftpUser: "bheinig1w",
    ftpPass: "tR7~vn!7!Fb(o7",
    disabled: false,
    createdBy: "Margarette Mauchline",
    createdAt: "2023-03-20T10:12:27Z",
    modifiedBy: "Beckie Heinig",
    modifiedAt: "2024-02-13T14:26:21Z",
  },
  {
    hqCd: 51,
    hqName: "Wal-Mart Stores Inc",
    storeCd: 99,
    storeName: "Straubel",
    email: "myendall1x@godaddy.com",
    ftpUser: "myendall1x",
    ftpPass: "nW9*3rt<",
    disabled: true,
    createdBy: "Max Ferrucci",
    createdAt: "2023-08-29T08:20:33Z",
    modifiedBy: "Merrili Yendall",
    modifiedAt: "2023-12-18T10:46:48Z",
  },
  {
    hqCd: 13,
    hqName: "Hyland's",
    storeCd: 96,
    storeName: "Paget",
    email: "hpedrozzi1y@tinypic.com",
    ftpUser: "hpedrozzi1y",
    ftpPass: 'fJ0~"<nMA!FyU',
    disabled: false,
    createdBy: "Mechelle Basterfield",
    createdAt: "2023-04-22T16:33:20Z",
    modifiedBy: "Hertha Pedrozzi",
    modifiedAt: "2023-07-08T04:36:31Z",
  },
  {
    hqCd: 91,
    hqName: "DAVA Pharmaceuticals, Inc.",
    storeCd: 13,
    storeName: "Stang",
    email: "bmatura1z@qq.com",
    ftpUser: "bmatura1z",
    ftpPass: "jF6@)cFp7&0gi",
    disabled: true,
    createdBy: "Erhard Mapletoft",
    createdAt: "2023-07-11T07:38:02Z",
    modifiedBy: "Buckie Matura",
    modifiedAt: "2023-08-22T23:39:19Z",
  },
  {
    hqCd: 99,
    hqName: "Baxter Healthcare Corporation",
    storeCd: 89,
    storeName: "Blaine",
    email: "rgiggs20@lulu.com",
    ftpUser: "rgiggs20",
    ftpPass: 'sS1%."*yZA*&j|',
    disabled: true,
    createdBy: "Stanfield Hauxley",
    createdAt: "2023-10-08T01:32:58Z",
    modifiedBy: "Rayshell Giggs",
    modifiedAt: "2023-04-21T20:18:07Z",
  },
  {
    hqCd: 48,
    hqName: "Kiss Products, Inc.",
    storeCd: 19,
    storeName: "Helena",
    email: "ldanieli21@dropbox.com",
    ftpUser: "ldanieli21",
    ftpPass: "tG2'~!,I_!`BH+R*",
    disabled: false,
    createdBy: "Kizzee O'Shields",
    createdAt: "2023-05-04T15:33:14Z",
    modifiedBy: "Loleta Danieli",
    modifiedAt: "2023-04-07T00:17:02Z",
  },
  {
    hqCd: 34,
    hqName: "Mylan Institutional Inc.",
    storeCd: 33,
    storeName: "6th",
    email: "atrulocke22@pbs.org",
    ftpUser: "atrulocke22",
    ftpPass: "zR0{U(ld",
    disabled: false,
    createdBy: "Terrell Ker",
    createdAt: "2023-09-03T17:56:35Z",
    modifiedBy: "Adara Trulocke",
    modifiedAt: "2023-03-22T07:32:41Z",
  },
  {
    hqCd: 23,
    hqName: "Preferred Pharmaceuticals, Inc.",
    storeCd: 25,
    storeName: "Almo",
    email: "gkinsman23@businessinsider.com",
    ftpUser: "gkinsman23",
    ftpPass: "yZ9~t|va~',\"7?Tf",
    disabled: false,
    createdBy: "Constantine Gourlie",
    createdAt: "2023-04-11T15:05:41Z",
    modifiedBy: "Gerhard Kinsman",
    modifiedAt: "2023-07-06T00:10:56Z",
  },
  {
    hqCd: 78,
    hqName: "Select Brand",
    storeCd: 14,
    storeName: "Clarendon",
    email: "lraffin24@usda.gov",
    ftpUser: "lraffin24",
    ftpPass: "xQ1)0x(XQd$Dour",
    disabled: false,
    createdBy: "Kordula Bennetts",
    createdAt: "2024-01-22T14:02:44Z",
    modifiedBy: "Lynsey Raffin",
    modifiedAt: "2023-10-16T19:07:10Z",
  },
  {
    hqCd: 61,
    hqName: "Macoven Pharmaceuticals",
    storeCd: 16,
    storeName: "Burrows",
    email: "bcowx25@imageshack.us",
    ftpUser: "bcowx25",
    ftpPass: "oP9*b70l%(ZK1z",
    disabled: false,
    createdBy: "Gisella Linny",
    createdAt: "2023-08-09T21:02:40Z",
    modifiedBy: "Burton Cowx",
    modifiedAt: "2023-10-12T09:32:21Z",
  },
  {
    hqCd: 19,
    hqName: "sanofi-aventis U.S. LLC",
    storeCd: 12,
    storeName: "Laurel",
    email: "ayeliashev26@naver.com",
    ftpUser: "ayeliashev26",
    ftpPass: "kA9`1YKU_x",
    disabled: false,
    createdBy: "Randie McCard",
    createdAt: "2024-01-18T01:17:40Z",
    modifiedBy: "Aurelie Yeliashev",
    modifiedAt: "2023-08-17T06:33:33Z",
  },
  {
    hqCd: 79,
    hqName: "Tween Brands Inc",
    storeCd: 19,
    storeName: "Ridge Oak",
    email: "ashipperbottom27@ucla.edu",
    ftpUser: "ashipperbottom27",
    ftpPass: "sN5!6X0lOB",
    disabled: true,
    createdBy: "Edwina Cardoso",
    createdAt: "2023-05-12T00:12:20Z",
    modifiedBy: "Andi Shipperbottom",
    modifiedAt: "2023-03-18T18:21:05Z",
  },
  {
    hqCd: 43,
    hqName: "Cantrell Drug Company",
    storeCd: 69,
    storeName: "Fisk",
    email: "mevers28@nbcnews.com",
    ftpUser: "mevers28",
    ftpPass: "aX5?.xy=}sFU",
    disabled: false,
    createdBy: "Maryann Coggles",
    createdAt: "2023-06-19T12:33:07Z",
    modifiedBy: "Manuel Evers",
    modifiedAt: "2023-05-06T18:10:34Z",
  },
  {
    hqCd: 88,
    hqName: "DIRECT RX",
    storeCd: 14,
    storeName: "Merchant",
    email: "tallix29@ucsd.edu",
    ftpUser: "tallix29",
    ftpPass: "aK1,VAVsSY1",
    disabled: true,
    createdBy: "Miltie Houson",
    createdAt: "2023-04-29T07:06:32Z",
    modifiedBy: "Tabbie Allix",
    modifiedAt: "2023-05-05T14:46:52Z",
  },
  {
    hqCd: 47,
    hqName: "Roxane Laboratories, Inc",
    storeCd: 71,
    storeName: "Manufacturers",
    email: "lnestor2a@boston.com",
    ftpUser: "lnestor2a",
    ftpPass: "pA2\\Mbz'",
    disabled: false,
    createdBy: "Frederica Rault",
    createdAt: "2023-06-04T20:55:07Z",
    modifiedBy: "Leland Nestor",
    modifiedAt: "2024-02-17T15:15:02Z",
  },
  {
    hqCd: 40,
    hqName: "State of Florida DOH Central Pharmacy",
    storeCd: 49,
    storeName: "Kennedy",
    email: "nshitliffe2b@e-recht24.de",
    ftpUser: "nshitliffe2b",
    ftpPass: 'dM0}}x"I`',
    disabled: false,
    createdBy: "Edithe Bickers",
    createdAt: "2023-07-10T20:22:33Z",
    modifiedBy: "Nichole Shitliffe",
    modifiedAt: "2023-12-05T01:59:46Z",
  },
  {
    hqCd: 44,
    hqName: "Cadila Healthcare Limited",
    storeCd: 70,
    storeName: "Artisan",
    email: "vcliffe2c@usatoday.com",
    ftpUser: "vcliffe2c",
    ftpPass: 'hG6>8Vf(L"|C4',
    disabled: true,
    createdBy: "Edgard Hucke",
    createdAt: "2023-02-19T17:32:04Z",
    modifiedBy: "Vincents Cliffe",
    modifiedAt: "2023-08-14T07:49:55Z",
  },
  {
    hqCd: 66,
    hqName: "Procter & Gamble Manufacturing Company",
    storeCd: 46,
    storeName: "Talmadge",
    email: "broff2d@wikimedia.org",
    ftpUser: "broff2d",
    ftpPass: "lQ8,z5Qal21%,A",
    disabled: false,
    createdBy: "Brittan Lansberry",
    createdAt: "2023-05-17T16:53:37Z",
    modifiedBy: "Bartel Roff",
    modifiedAt: "2023-08-11T13:02:35Z",
  },
  {
    hqCd: 4,
    hqName: "REMEDYREPACK INC.",
    storeCd: 32,
    storeName: "Holmberg",
    email: "kkondratyuk2e@google.ru",
    ftpUser: "kkondratyuk2e",
    ftpPass: "qM7)kS}H$cN",
    disabled: false,
    createdBy: "Donnell Christopher",
    createdAt: "2023-06-05T20:57:19Z",
    modifiedBy: "Kathrine Kondratyuk",
    modifiedAt: "2023-11-03T22:22:47Z",
  },
  {
    hqCd: 44,
    hqName: "Ventura Corporation Ltd.",
    storeCd: 38,
    storeName: "Welch",
    email: "fwilshere2f@delicious.com",
    ftpUser: "fwilshere2f",
    ftpPass: "pQ2/~R%OdRzvhc$",
    disabled: false,
    createdBy: "Camilla Matskiv",
    createdAt: "2023-04-02T23:14:26Z",
    modifiedBy: "Francoise Wilshere",
    modifiedAt: "2023-07-13T07:43:59Z",
  },
  {
    hqCd: 56,
    hqName: "MEGASOL COSMETIC GMBH",
    storeCd: 96,
    storeName: "Declaration",
    email: "tcrain2g@smugmug.com",
    ftpUser: "tcrain2g",
    ftpPass: "vJ1%@%j|gj>G~s",
    disabled: true,
    createdBy: "Kara-lynn Jarnell",
    createdAt: "2023-08-12T10:26:17Z",
    modifiedBy: "Theodore Crain",
    modifiedAt: "2023-03-07T22:42:33Z",
  },
  {
    hqCd: 86,
    hqName: "EQUATE (Walmart Stores, Inc.)",
    storeCd: 41,
    storeName: "5th",
    email: "mhardan2h@quantcast.com",
    ftpUser: "mhardan2h",
    ftpPass: "gJ4_R5FkbI{",
    disabled: true,
    createdBy: "Valeria Blagburn",
    createdAt: "2023-10-19T04:48:50Z",
    modifiedBy: "Meir Hardan",
    modifiedAt: "2023-10-20T13:18:38Z",
  },
  {
    hqCd: 54,
    hqName: "Apotex Corp",
    storeCd: 4,
    storeName: "Rusk",
    email: "lmccard2i@gravatar.com",
    ftpUser: "lmccard2i",
    ftpPass: "rM3(#+v|",
    disabled: false,
    createdBy: "Michal Pitrasso",
    createdAt: "2023-03-13T00:51:38Z",
    modifiedBy: "Leland McCard",
    modifiedAt: "2023-04-05T18:25:29Z",
  },
  {
    hqCd: 46,
    hqName: "NATURE REPUBLIC CO., LTD.",
    storeCd: 63,
    storeName: "Walton",
    email: "afehely2j@myspace.com",
    ftpUser: "afehely2j",
    ftpPass: "lZ3&@\\wv`FQOa",
    disabled: false,
    createdBy: "Chickie Fettiplace",
    createdAt: "2024-02-11T06:52:57Z",
    modifiedBy: "Anna-diane Fehely",
    modifiedAt: "2023-06-18T10:53:46Z",
  },
  {
    hqCd: 64,
    hqName: "DUSA Pharmaceuticals, Inc.",
    storeCd: 94,
    storeName: "Superior",
    email: "taron2k@usatoday.com",
    ftpUser: "taron2k",
    ftpPass: "dS8,Z1Mj9IqK",
    disabled: true,
    createdBy: "Dede Falconar",
    createdAt: "2023-06-20T10:19:18Z",
    modifiedBy: "Tuck Aron",
    modifiedAt: "2023-10-26T08:02:21Z",
  },
  {
    hqCd: 99,
    hqName: "L'Oreal USA Products Inc",
    storeCd: 75,
    storeName: "Haas",
    email: "tlaval2l@icio.us",
    ftpUser: "tlaval2l",
    ftpPass: "vI6~Wr\\VHQI0sYS",
    disabled: false,
    createdBy: "Palm Kyme",
    createdAt: "2023-06-11T08:42:55Z",
    modifiedBy: "Traver Laval",
    modifiedAt: "2023-06-22T13:31:23Z",
  },
  {
    hqCd: 61,
    hqName: "Contract Pharmacy Services-PA",
    storeCd: 98,
    storeName: "Hoffman",
    email: "cpoli2m@umich.edu",
    ftpUser: "cpoli2m",
    ftpPass: "uA7@GvyoD>fstJ",
    disabled: false,
    createdBy: "Cherice Ferber",
    createdAt: "2023-09-03T10:19:34Z",
    modifiedBy: "Chloris Poli",
    modifiedAt: "2023-10-26T08:13:40Z",
  },
  {
    hqCd: 17,
    hqName: "Geri-Care Pharmaceuticals, Corp",
    storeCd: 75,
    storeName: "Manley",
    email: "rskowcraft2n@globo.com",
    ftpUser: "rskowcraft2n",
    ftpPass: "wI0%%zPhsLHmC$",
    disabled: false,
    createdBy: "Bowie McGilvray",
    createdAt: "2023-10-09T08:17:07Z",
    modifiedBy: "Reinald Skowcraft",
    modifiedAt: "2023-11-25T13:00:59Z",
  },
  {
    hqCd: 30,
    hqName: "Kramer Novis",
    storeCd: 22,
    storeName: "Killdeer",
    email: "gsecombe2o@harvard.edu",
    ftpUser: "gsecombe2o",
    ftpPass: "oF2@`Q%a/2t",
    disabled: false,
    createdBy: "Moyra Fauning",
    createdAt: "2024-01-19T01:25:34Z",
    modifiedBy: "Gerri Secombe",
    modifiedAt: "2023-03-01T03:10:27Z",
  },
  {
    hqCd: 39,
    hqName: "Roxane Laboratories, Inc",
    storeCd: 78,
    storeName: "American Ash",
    email: "ctocher2p@wsj.com",
    ftpUser: "ctocher2p",
    ftpPass: 'iA7"j=T()',
    disabled: false,
    createdBy: "Cy Pergens",
    createdAt: "2023-06-06T22:00:56Z",
    modifiedBy: "Chaunce Tocher",
    modifiedAt: "2023-05-20T17:40:54Z",
  },
  {
    hqCd: 33,
    hqName: "SKINFOOD CO., LTD.",
    storeCd: 43,
    storeName: "Ronald Regan",
    email: "lveale2q@craigslist.org",
    ftpUser: "lveale2q",
    ftpPass: "lH0%jPv)a",
    disabled: true,
    createdBy: "Kerry Burndred",
    createdAt: "2023-12-03T20:16:16Z",
    modifiedBy: "Lyle Veale",
    modifiedAt: "2023-11-08T19:36:31Z",
  },
  {
    hqCd: 7,
    hqName: "Rebel Distributors Corp",
    storeCd: 70,
    storeName: "Brown",
    email: "lalderwick2r@sakura.ne.jp",
    ftpUser: "lalderwick2r",
    ftpPass: "uP2=?kfm`D~",
    disabled: false,
    createdBy: "Abbey Cheeld",
    createdAt: "2023-05-11T06:53:30Z",
    modifiedBy: "Letisha Alderwick",
    modifiedAt: "2023-09-13T17:14:13Z",
  },
];
